import json
import logging
import boto3
import json
from botocore.exceptions import NoCredentialsError

logger = logging.getLogger("CEE_bounce_reporter")
logger.setLevel(logging.INFO)
AWS_REGION = "ap-southeast-2"

def get_email_table():
    email_table_data = "<table><thead><tr><th>Mail ID</th><th>Subject</th><th>Email Address</th><th>Error</th><th>File Name</th></tr></thead><tbody><tr><td></td><td></td><td></td><td></td><td></td></tr></tbody></table>"

def get_ftp_table():
    ftp_table_data = "<table><thead><tr><th>Agency Name</th><th>Contact</th><th>File Name</th></tr></thead><tbody><tr><td></td><td></td><td></td></tr></tbody></table>"

# Email - REPORT|Holdings|email|Bounce|source|subject|['venmohanu@test.code7swm.com.au']|filename.txt
# FTP   - REPORT|Holdings|ftp|Success|agencyName|contactEmail|Holdings_2024-04-12 0702 000343_SEVNET.h.zip
def generate_email_data(log_datum):
    overall_data = {
                    "holdings": {
                        "totalEmailCount": "",
                        "totalFtpCount": "",
                        "failedEmails": {
                        "count": "",
                        "details": [
                            {
                                "source": "",
                                "subject": "",
                                "destination": "",
                                "error": "",
                                "attachmentName": "",
                            }
                        ]
                        },
                        "deliveredEmailCount": "",
                        "failedFtps": {
                        "count": 0,
                        "details": [
                            {
                                "agencyName": "",
                                "contact": "",
                                "fileName": "",
                            }
                        ]
                        },
                        "deliveredFtpCount": 0,
                    }
                    }

    for log_data in log_datum:
        holdings_ftp_count = 0
        holdings_email_count = 0
        log_split = log_data.split("|")
        if log_split[3] == "ftp" and log_split[4] == "success":
            overall_data["holdings"]["deliveredFtpCount"] += 1
        else:
            overall_data["holdings"]["failedFtps"]["count"] += 1
            overall_data["holdings"]["failedFtps"]["details"][holdings_ftp_count]["agencyName"] = log_split[5]
            overall_data["holdings"]["failedFtps"]["details"][holdings_ftp_count]["contact"] = log_split[6]
            overall_data["holdings"]["failedFtps"]["details"][holdings_ftp_count]["fileName"] = log_split[7]
            holdings_ftp_count += 1
        
        if log_split[3] == "email" and log_split[1] == "Delivery":
            overall_data["holdings"]["deliveredEmailCount"] += 1
        else:
            overall_data["holdings"]["failedEmails"]["count"] += 1
            overall_data["holdings"]["failedEmails"]["details"][holdings_email_count]["source"] = log_split[5]
            overall_data["holdings"]["failedEmails"]["details"][holdings_email_count]["subject"] = log_split[6]
            overall_data["holdings"]["failedEmails"]["details"][holdings_email_count]["fileName"] = log_split[7]
            holdings_email_count += 1
        
    title = "<b>The Holdings Delivery Report for </b><br><br>"
    lmk__report_data = "<b>TX Date:</b><p>Number of Files generated by Landmark:</p><br>"
    email_report_success_data = "<b>Emails</b><br><p>Total successful emails delivered:"
    email_report_failure_data = f"<br>Total unsuccessful emails:</p><b>Unsuccessful Email Details</b><br><br>{table_data}"
    ftp_report_success_data = "<b>FTP</b><br><p>Total successful FTP transfers:"
    ftp_report_failure_data = f"<br>Total unsuccessful FTP:</p><b>Unsuccessful FTP Details</b><br><br>{table_data}"

def lambda_handler(event, context):
    # Extract log data from CloudWatch Logs
    log_group_name = "/aws/lambda/r2sit/CEESESNotificationHandler"
    log_stream_name = "r2sit_cee_notification_stream"

    logs_client = boto3.client("logs")
    response = logs_client.get_log_events(
        logGroupName=log_group_name,
        logStreamName=log_stream_name,
        limit=10,
        startFromHead=True,
    )

    log_events = response.get("events", [])

    # Extract relevant information from log events
    extracted_data = []
    for log_event in log_events:
        log_event = str(log_event['message'])
        if log_event[:6] == "REPORT":
            extracted_data.append(log_event)

    # Send an email with the extracted log data
    sender = "delivery_report@test.code7swm.com.au"
    recipient = "venmohanu@seven.com.au"
    subject = "Holdings Delivery Report"
    # Construct the email body with the extracted log data
    generate_email_data(extracted_data)
    body = f""
    # body = "\n".join(extracted_data)
    logger.info(body)
    try:
        # Send the email using SES
        ses_client = boto3.client("ses", region_name=AWS_REGION)

        response = ses_client.send_email(
                Destination={'ToAddresses': [recipient]},
                Message={
                    'Subject': {'Charset': 'UTF-8','Data': subject},
                    'Body': {
                        'Html': {
                            'Charset': 'UTF-8',
                            'Data': body,
                        }
                    }
                },
                Source=sender
            )

        logger.info(f"Email sent successfully. Message ID: {response['MessageId']}")
    except NoCredentialsError as e:
        logger.info("Credentials not available")

    except Exception as e:
        logger.info(f"Error sending email: {e}")
